# -*- coding: utf-8 -*-
"""enrich_change_logs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13NsrQXDx_VLzDquPtc1XuC178w1i7LQT
"""

import pandas as pd
import os

change_logs = [
    "data/changelogs/Day2_changes.csv",
    "data/changelogs/Day3_changes.csv"
]

enriched_folder = "data/enriched/"
os.makedirs(enriched_folder, exist_ok=True)

# Columns for enriched dataset
enriched_columns = [
    "CIN", "COMPANY_NAME", "STATE", "STATUS",
    "SOURCE", "FIELD", "SOURCE_URL", "SECTOR", "DIRECTORS", "REGISTERED_OFFICE"
]

# Empty list to store enriched data
enriched_data = []

# Loop through change logs
for log_file in change_logs:
    df = pd.read_csv(log_file)

    # Take a sample or all companies
    sample_df = df.head(50)  # change to len(df) if you want all

    for idx, row in sample_df.iterrows():
        # Simulated enrichment (for now, using dummy values or placeholders)
        enriched_data.append({
            "CIN": row["CIN"],
            "COMPANY_NAME": row["CIN"],  # For demo, replace with real company name from log if available
            "STATE": row.get("Date", ""),  # Using Date column as placeholder for demo
            "STATUS": row.get("Change_Type", ""),
            "SOURCE": "Simulated",  # e.g., ZaubaCorp/API
            "FIELD": row.get("Field_Changed", ""),
            "SOURCE_URL": "https://www.zaubacorp.com/",  # placeholder
            "SECTOR": "IT/Services",  # placeholder
            "DIRECTORS": "John Doe",  # placeholder
            "REGISTERED_OFFICE": "Mumbai"  # placeholder
        })

# Convert to DataFrame and save
enriched_df = pd.DataFrame(enriched_data, columns=enriched_columns)
output_file = os.path.join(enriched_folder, "enriched_sample.csv")
enriched_df.to_csv(output_file, index=False)
print(f"✅ Enriched dataset saved: {output_file}")

change_logs = [
    "/content/MCA-Insight-Engine/Data/Change logs/Day2_changes.csv",
    "/content/MCA-Insight-Engine/Data/Change logs/Day3_changes.csv"
]

enriched_folder = "/content/MCA-Insight-Engine/Data/Enriched"
os.makedirs(enriched_folder, exist_ok=True)

# Columns for enriched dataset
enriched_columns = [
    "CIN", "COMPANY_NAME", "STATE", "STATUS",
    "SOURCE", "FIELD", "SOURCE_URL", "SECTOR", "DIRECTORS", "REGISTERED_OFFICE"
]

# Empty list to store enriched data
enriched_data = []

# Loop through change logs
for log_file in change_logs:
    df = pd.read_csv(log_file)

    # Take a sample or all companies
    sample_df = df.head(50)  # change to len(df) if you want all

    for idx, row in sample_df.iterrows():
        # Simulated enrichment (for now, using dummy values or placeholders)
        enriched_data.append({
            "CIN": row["CIN"],
            "COMPANY_NAME": row["CIN"],  # For demo, replace with real company name from log if available
            "STATE": row.get("Date", ""),  # Using Date column as placeholder for demo
            "STATUS": row.get("Change_Type", ""),
            "SOURCE": "Simulated",  # e.g., ZaubaCorp/API
            "FIELD": row.get("Field_Changed", ""),
            "SOURCE_URL": "https://www.zaubacorp.com/",  # placeholder
            "SECTOR": "IT/Services",  # placeholder
            "DIRECTORS": "John Doe",  # placeholder
            "REGISTERED_OFFICE": "Mumbai"  # placeholder
        })

# Convert to DataFrame and save
enriched_df = pd.DataFrame(enriched_data, columns=enriched_columns)
output_file = os.path.join(enriched_folder, "enriched_sample.csv")
enriched_df.to_csv(output_file, index=False)
print(f"✅ Enriched dataset saved: {output_file}")