# -*- coding: utf-8 -*-
"""Simulate_Daily_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a4LVWbQf-WsKZUhbCvRJf0knoez7_Ew7
"""

import pandas as pd
from copy import deepcopy

# ----------------------------
# Columns based on the master dataset
# ----------------------------
columns_master = [
    'CORPORATE_IDENTIFICATION_NUMBER', 'COMPANY_NAME', 'COMPANY_STATUS',
    'COMPANY_CLASS', 'COMPANY_CATEGORY', 'COMPANY_SUB_CATEGORY',
    'DATE_OF_REGISTRATION', 'REGISTERED_STATE', 'AUTHORIZED_CAP',
    'PAIDUP_CAPITAL', 'INDUSTRIAL_CLASS',
    'PRINCIPAL_BUSINESS_ACTIVITY_AS_PER_CIN', 'REGISTERED_OFFICE_ADDRESS',
    'REGISTRAR_OF_COMPANIES', 'EMAIL_ADDR', 'LATEST_YEAR_ANNUAL_RETURN',
    'LATEST_YEAR_FINANCIAL_STATEMENT', 'STATE'
]

# ----------------------------
# 1️⃣ Day 1 - Base Dataset
# ----------------------------
day1_data = [
    ["U12345MH2010PLC100001", "Alpha Tech Pvt Ltd", "Active", "Private", "Limited", "By Shares",
     "2010-05-12", "Maharashtra", 5000000, 5000000, "Manufacturing",
     "Software Development", "Mumbai Office, Mumbai", "ROC-Mumbai", "alpha@tech.com", 2023, 2023, "MH"],

    ["U23456GJ2012PLC200002", "Beta Corp Ltd", "Active", "Private", "Limited", "By Shares",
     "2012-11-23", "Gujarat", 8000000, 7500000, "Construction",
     "Construction Services", "Ahmedabad Office, Ahmedabad", "ROC-Ahmedabad", "beta@corp.com", 2023, 2023, "GJ"],

    ["U34567DL2015PLC300003", "Gamma Solutions Pvt Ltd", "Strike Off", "Private", "Limited", "By Shares",
     "2015-07-10", "Delhi", 12000000, 12000000, "IT Services",
     "IT Consulting", "Delhi Office, Delhi", "ROC-Delhi", "gamma@solutions.com", 2023, 2023, "DL"],

    ["U45678TN2018PLC400004", "Delta Industries Ltd", "Active", "Public", "Limited", "By Shares",
     "2018-02-19", "Tamil Nadu", 15000000, 14500000, "Textiles",
     "Textile Manufacturing", "Chennai Office, Chennai", "ROC-Chennai", "delta@industries.com", 2023, 2023, "TN"],

    ["U56789KA2020PLC500005", "Epsilon Traders Pvt Ltd", "Active", "Private", "Limited", "By Shares",
     "2020-09-01", "Karnataka", 6000000, 5500000, "Retail",
     "Retail Services", "Bangalore Office, Bangalore", "ROC-Bangalore", "epsilon@traders.com", 2023, 2023, "KA"]
]

day1 = pd.DataFrame(day1_data, columns=columns_master)
day1.to_csv("day1_master.csv", index=False)
print("✅ day1_master.csv created")

# ----------------------------
# 2️⃣ Day 2 - Simulate Updates
# ----------------------------
day2 = deepcopy(day1)

# a) Add a new company
new_company_day2 = [
    "U67890MH2021PLC600006", "Zeta Innovations Pvt Ltd", "Active", "Private", "Limited", "By Shares",
    "2021-06-15", "Maharashtra", 7000000, 6500000, "FinTech",
    "Financial Services", "Mumbai Office, Mumbai", "ROC-Mumbai", "zeta@innovations.com", 2023, 2023, "MH"
]
day2 = pd.concat([day2, pd.DataFrame([new_company_day2], columns=columns_master)], ignore_index=True)

# b) Remove a company (simulate deregistration)
day2 = day2[day2["CORPORATE_IDENTIFICATION_NUMBER"] != "U34567DL2015PLC300003"]

# c) Update fields for some companies
day2.loc[day2["CORPORATE_IDENTIFICATION_NUMBER"] == "U45678TN2018PLC400004", "COMPANY_STATUS"] = "Amalgamated"
day2.loc[day2["CORPORATE_IDENTIFICATION_NUMBER"] == "U23456GJ2012PLC200002", "AUTHORIZED_CAP"] = 9000000

day2.to_csv("day2_master.csv", index=False)
print("✅ day2_master.csv created")

# ----------------------------
# 3️⃣ Day 3 - More Updates
# ----------------------------
day3 = deepcopy(day2)

# a) Add another new company
new_company_day3 = [
    "U78901KA2023PLC700007", "Theta Systems Ltd", "Active", "Private", "Limited", "By Shares",
    "2023-03-22", "Karnataka", 10000000, 9000000, "Software",
    "Software Development", "Bangalore Office, Bangalore", "ROC-Bangalore", "theta@systems.com", 2023, 2023, "KA"
]
day3 = pd.concat([day3, pd.DataFrame([new_company_day3], columns=columns_master)], ignore_index=True)

# b) Change company status
day3.loc[day3["CORPORATE_IDENTIFICATION_NUMBER"] == "U56789KA2020PLC500005", "COMPANY_STATUS"] = "Strike Off"

# c) Modify paid-up capital
day3.loc[day3["CORPORATE_IDENTIFICATION_NUMBER"] == "U12345MH2010PLC100001", "PAIDUP_CAPITAL"] = 5200000

day3.to_csv("day3_master.csv", index=False)
print("✅ day3_master.csv created")

print("\n🎉 Simulation Complete! Files generated:")
print(" - day1_master.csv")
print(" - day2_master.csv")
print(" - day3_master.csv")